# docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=backend -p 3306:3306 mysql:8.0

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ohksj77/dnd-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_SCHEMA: backend
      DB_USERNAME: root
      DB_PASSWORD: 1234
    networks:
      - app-tier

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: backend
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-tier

networks:
  app-tier:

volumes:
  mysql-data: null
