# docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=backend -p 3306:3306 mysql:8.0

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: backend
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: null
